output_dir: ./output/99/


gradient_checkpointing: false
per_device_train_batch_size: 18
gradient_accumulation_steps: 1
learning_rate: 5.0e-7
max_length: 512
max_new_tokens: 256
max_completion_length: 256
generate_temperature: 0.75
beta: 0.05
bf16: true
dataset_num_proc: 1
num_astar: 2
torch_empty_cache_steps: 1
num_train_epochs: 1
eval_strategy: "no"
eval_steps: 100
save_strategy: "steps"
save_steps: 1000
logging_steps: 100

push_to_hub: false
hub_model_id: Eehan/Qwen2-0.5B-drpo-imdb_origin
report_to: 
  - wandb
is_bt_model: true
preference_model_id: siebert/sentiment-roberta-large-english
preference_model_kwargs:
  indifferent: false
  random: false
  reverse: false
ratio_processing: clip
clipbound: 5.0
forward_temperature: 0.75
max_grad_norm: 0.05
loss1_only: true
loss2_only: false